name: pegasus_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  path_provider: ^2.1.1
  formz: ^0.5.1
  dartz: ^0.10.1

  # Networking
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.2

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^11.0.0

  # UI/Assets
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  intl: ^0.18.1

  # Core
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
